<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Wszystkie testy - ostateczna wersja</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>b1ac7141-5ecc-4819-b949-e20537574b95</testSuiteGuid>
   <testCaseLink>
      <guid>0c9973c3-7413-4f02-a668-6a659a790494</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F01 - Logowanie do strony/T1 - Logowanie jako Customer_Agent_Admin_Supplier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bc6a57c4-abc0-4ab4-9818-6b7417a3256e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dane testowe - ostateczna wersja/Dane logowania</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>bc6a57c4-abc0-4ab4-9818-6b7417a3256e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>login_input</value>
         <variableId>192c4bae-31da-4674-86d5-abb46d1004d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bc6a57c4-abc0-4ab4-9818-6b7417a3256e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password_input</value>
         <variableId>0eafc96a-a8ac-4ea3-a4b0-8fe8b80f207c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>34d26f68-250e-4122-be80-506df92fa320</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F01 - Logowanie do strony/T2 - Logowanie przy użyciu nieprawidłowych danych</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>def3580d-449f-4abd-85e8-5f644d9d73c2</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dane testowe - ostateczna wersja/Nieprawidłowe dane logowania</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>def3580d-449f-4abd-85e8-5f644d9d73c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>login_input</value>
         <variableId>8d7b0a81-b339-4ad0-91c8-817c10eebaa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>def3580d-449f-4abd-85e8-5f644d9d73c2</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password_input</value>
         <variableId>007e369f-c575-41a8-9593-002abac9ec19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ffabe50-3b4a-4c64-8270-3fe38d6c6041</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F02 -Podstawowe funkcjonalności strony/Formularz kontaktowy/T3 - Weryfikacja poprawnego działania formularza kontaktowego (User Customer)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>43322c92-d1bf-4dba-80e1-a78085b0895b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dane testowe - ostateczna wersja/Wiadomość</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>43322c92-d1bf-4dba-80e1-a78085b0895b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message_area</value>
         <variableId>4f9b1d4c-a463-40ba-b1b7-c30eabeb22d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2988bb9b-f7e7-4837-84a9-2b6f22619957</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F02 -Podstawowe funkcjonalności strony/Wersje strony/T4 - Weryfikacja poprawnego wyświetlania się strony w języku rosyjskim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5d65c6b-5d57-4835-9b19-4f26bc1ab745</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83a95569-8a3e-4432-9138-96c70379fd77</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F02 -Podstawowe funkcjonalności strony/Wersje strony/T5 - Weryfikacja poprawnego wyświetlania się strony w języku hiszpańskim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c35842-285d-4d34-a298-4500d0f06a53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b2858a79-2155-412b-a7bf-110d378d51e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T6 - Sprawdzenie działania wyszukiwarki lotów (dostępne destynacje)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>de9c32a5-e79a-4e7e-a207-f4172f2d5034</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dane testowe - ostateczna wersja/Dostępne destynacje (loty)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>de9c32a5-e79a-4e7e-a207-f4172f2d5034</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>1</value>
         <variableId>20780149-14f6-48be-b328-6457803e472f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de9c32a5-e79a-4e7e-a207-f4172f2d5034</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>2</value>
         <variableId>5548b44e-beef-4691-bd99-58a30904650a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e2f1b91-87e5-45ab-8710-7a6f0aea3c64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T7 - Sprawdzenie działania wyszukiwarki lotów (dostępne destynacje)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c93f947-8c86-41d3-974e-b864842d8130</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34ecac11-e941-4d83-8bee-67d72c53bad0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e241e4e-87f4-4089-a30c-a159067558e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T8 - Sprawdzenie działania wyszukiwarki lotów (dostępne destynacje)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2be8f3e7-5b42-41e7-bcb1-fb42d959d74c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ddd272d-4a30-4cfc-b00b-9ca045dfc7a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3eadc9da-df72-417e-b829-4a22381a87b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T9 - Sprawdzenie działania wyszukiwarki lotów (niedostępne destynacje)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ab1ff34d-eae2-48cc-8464-2b7d09b0d4ad</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dane testowe - ostateczna wersja/Nidostępne destynacje</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ab1ff34d-eae2-48cc-8464-2b7d09b0d4ad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cityName_input</value>
         <variableId>65d42b35-e94f-4b2e-80ea-e5ae25d6cafa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ab1ff34d-eae2-48cc-8464-2b7d09b0d4ad</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ciyName_input2</value>
         <variableId>2fb91ef3-c882-420d-9375-5bd41df516cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a5d4a7af-a3e7-4565-818b-96855eaec1ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Dubai/T10 - Weryfikacja filtrowania wg oceny</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5228ad-3da8-42ae-9120-a706128a4fc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4b2ab054-09d4-41ef-9c70-2485c7990137</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Dubai/T11 - Weryfikacja filtrowania wg nazwy</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1dc0d6df-f43c-4a28-8285-091224fd5e23</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dane testowe - ostateczna wersja/Hotele - Dubai</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65d0eb4b-5076-478c-831b-573d12354a59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1dc0d6df-f43c-4a28-8285-091224fd5e23</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>name_hotel</value>
         <variableId>0ef47a99-17e5-47f5-b32f-9f0eb4390110</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1787166-2c52-4e28-b7ad-80544848642b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Dubai/T12 - Sprawdzenie działania wyszukiwarki noclegów</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8ffd0d0-8fa8-431f-af6e-83f59d626402</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae3575da-6460-40ce-9271-a75e5cec469a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Istanbul/T12 - Weryfikacja filtrowania wg nazwy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b131f065-f426-49cd-ba09-82bb5d0929f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a44cd52-1328-4c13-9e80-b1da2abb706e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb19e828-54ab-4086-b5db-f800a821622a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Istanbul/T13 - Sprawdzenie działania wyszukiwarki noclegów</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae12110-6ebe-49ba-a975-955d53869af7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a9f1b0e8-0ab1-4b48-903b-a953f00063fc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Istanbul/T14 - Weryfikacja filtrowania wg oceny</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>345a76e0-0d00-490c-898b-eb4310b0ea7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8e93f5f-51b1-4287-9db6-2d02f86316bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Singapore/T15 - Weryfikacja filtrowania wg nazwy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88236ae0-88f7-4314-b279-94e002ae3ee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1017651c-6c74-42fa-aff4-31ef98ca7b5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1bb44584-e13c-40b9-8177-34d33b5eadae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Singapore/T16 - Weryfikacja filtrowania wg oceny</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef38fd59-2a19-45cf-846e-e9336faf2ee8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a209b18e-02f3-4403-8a3a-f27b518a5f85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Singapore/T17 - Sprawdzenie działania wyszukiwarki noclegów</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5d8fc62-3b73-4b63-88ee-55c291eb5c12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fa074e08-8c37-4fb3-9307-f0533f275162</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F05 -Rezerwacja lotów/T18 - Rezerwacja lotu (loty proponowane)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ee3316cf-c12a-48ad-8cea-a132715c753d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F05 -Rezerwacja lotów/T19 - Rezerwacja lotu (loty proponowane)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9959fd9c-6fb4-469e-9289-7789ee477231</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F06 -Rezerwacja noclegów/T20 - Rezerwacja noclegu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7c41bce-6af2-4334-be52-fb7112e7e101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6ec7683c-a156-4c3b-9fb2-8e64acb47c98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F06 -Rezerwacja noclegów/T21 - Rezerwacja noclegu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4021b5c9-2ae9-4d24-a3aa-8afc5183fe29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d92df3d2-04bb-453c-9285-698153723a5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F07 -Rezerwacja wycieczek/T22 - Rezerwacja wycieczki dla 3 osób</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>351284f8-0c04-433d-b0fe-edf5be6eaf8d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F07 -Rezerwacja wycieczek/T23 - Rezerwacja wycieczki rodzinnej</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
