<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Wszystkie testy</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>54b2f017-7e7a-46aa-b945-71070ff9f31e</testSuiteGuid>
   <testCaseLink>
      <guid>132d2ddb-6dbe-4fab-b612-fcaa8e53d528</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F01 - Logowanie do strony/T1 - Logowanie jako Customer_Agent_Admin_Supplier</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0a9a572c-6006-4d71-b82b-5ea3b48837a3</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/New Test Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>0a9a572c-6006-4d71-b82b-5ea3b48837a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>login_input</value>
         <variableId>192c4bae-31da-4674-86d5-abb46d1004d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0a9a572c-6006-4d71-b82b-5ea3b48837a3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password_input</value>
         <variableId>0eafc96a-a8ac-4ea3-a4b0-8fe8b80f207c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5001a454-05e8-442f-a17f-c5dd4532562b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F01 - Logowanie do strony/T2 - Logowanie przy użyciu nieprawidłowych danych</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1c0303e8-fd9f-4162-8af2-af771ca54f79</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Invalid_LogData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>1c0303e8-fd9f-4162-8af2-af771ca54f79</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>login_input</value>
         <variableId>8d7b0a81-b339-4ad0-91c8-817c10eebaa1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1c0303e8-fd9f-4162-8af2-af771ca54f79</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password_input</value>
         <variableId>007e369f-c575-41a8-9593-002abac9ec19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0f008b2d-b6dd-448c-87ab-3beead59ad7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F02 -Podstawowe funkcjonalności strony/Formularz kontaktowy/T3 - Weryfikacja poprawnego działania formularza kontaktowego (User Customer)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>65eb51af-f134-453a-9428-8f94ff415b0b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Message</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>65eb51af-f134-453a-9428-8f94ff415b0b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>message_area</value>
         <variableId>4f9b1d4c-a463-40ba-b1b7-c30eabeb22d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04ca9dd2-6d37-4cff-9d16-14732087519a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F02 -Podstawowe funkcjonalności strony/Wersje strony/T5 - Weryfikacja poprawnego wyświetlania się strony w języku hiszpańskim</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6c35842-285d-4d34-a298-4500d0f06a53</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24aa8d17-6097-4fe6-b00f-553aa8fb6595</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T6 - Sprawdzenie działania wyszukiwarki lotów (dostępne destynacje)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>af084c8f-ddff-44e1-9eb1-75dc89371cf9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Dostępne destynacje (loty)</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>af084c8f-ddff-44e1-9eb1-75dc89371cf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>1</value>
         <variableId>20780149-14f6-48be-b328-6457803e472f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>af084c8f-ddff-44e1-9eb1-75dc89371cf9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>2</value>
         <variableId>5548b44e-beef-4691-bd99-58a30904650a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0578238-0c94-4909-afa5-554f794d55f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T7 - Sprawdzenie działania wyszukiwarki lotów (dostępne destynacje)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c93f947-8c86-41d3-974e-b864842d8130</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34ecac11-e941-4d83-8bee-67d72c53bad0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbbc3a37-6a03-4033-a172-0e561de002e4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T8 - Sprawdzenie działania wyszukiwarki lotów (dostępne destynacje)</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2be8f3e7-5b42-41e7-bcb1-fb42d959d74c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ddd272d-4a30-4cfc-b00b-9ca045dfc7a3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebeb5270-0f8c-4f67-85f6-6d7cf1cfa1d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F03 -Wyszukiwarka lotów/T9 - Sprawdzenie działania wyszukiwarki lotów (niedostępne destynacje)</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>99e9d6ba-6dc1-4288-9540-71b46ca1d1a4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Niedostępne destynacje</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>99e9d6ba-6dc1-4288-9540-71b46ca1d1a4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>cityName_input</value>
         <variableId>65d42b35-e94f-4b2e-80ea-e5ae25d6cafa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>99e9d6ba-6dc1-4288-9540-71b46ca1d1a4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ciyName_input2</value>
         <variableId>2fb91ef3-c882-420d-9375-5bd41df516cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8a3f692-ad59-421f-8b87-0adbf9987e9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Dubai/T10 - Weryfikacja filtrowania wg oceny</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca5228ad-3da8-42ae-9120-a706128a4fc6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8dbd089-a224-430b-8f46-7c1869b013e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Dubai/T11 - Weryfikacja filtrowania wg nazwy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65d0eb4b-5076-478c-831b-573d12354a59</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ef47a99-17e5-47f5-b32f-9f0eb4390110</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>120c98ca-1ec7-42a8-af88-abfd3233c3ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Dubai/T12 - Sprawdzenie działania wyszukiwarki noclegów</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8ffd0d0-8fa8-431f-af6e-83f59d626402</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ffcc0a2d-1377-471f-bc3a-ea34749f047c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Istanbul/T12 - Weryfikacja filtrowania wg nazwy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b131f065-f426-49cd-ba09-82bb5d0929f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a44cd52-1328-4c13-9e80-b1da2abb706e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a07b78d7-f0d2-41e8-a294-8ba2d828b861</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Istanbul/T13 - Sprawdzenie działania wyszukiwarki noclegów</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae12110-6ebe-49ba-a975-955d53869af7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>324e1800-fe3e-486c-b945-cb9def141f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Istanbul/T14 - Weryfikacja filtrowania wg oceny</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>345a76e0-0d00-490c-898b-eb4310b0ea7b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9961d9ae-554f-48f9-bf2c-620e9d24723e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Singapore/T15 - Weryfikacja filtrowania wg nazwy</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88236ae0-88f7-4314-b279-94e002ae3ee8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1017651c-6c74-42fa-aff4-31ef98ca7b5c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>945c895c-31a3-4dec-bbb8-65b4356b5378</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Singapore/T16 - Weryfikacja filtrowania wg oceny</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef38fd59-2a19-45cf-846e-e9336faf2ee8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c290a432-942d-43de-a275-c753cbff11d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F04 -Wyszukiwarka noclegów/Singapore/T17 - Sprawdzenie działania wyszukiwarki noclegów</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b5d8fc62-3b73-4b63-88ee-55c291eb5c12</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>104738d6-1dbf-4144-acf4-6ab734dbf475</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F05 -Rezerwacja lotów/T18 - Rezerwacja lotu (loty proponowane)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3db8f384-7204-4172-a43b-71bc50c8b526</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F05 -Rezerwacja lotów/T19 - Rezerwacja lotu (loty proponowane)</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>699e9497-9807-4564-91b1-8163c8e65520</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F07 -Rezerwacja wycieczek/T22 - Rezerwacja wycieczki dla 3 osób</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0c5f8357-6b7d-4bff-ad3f-c2fb3a3965eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F07 -Rezerwacja wycieczek/T23 - Rezerwacja wycieczki rodzinnej</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b2d11ed5-ec11-4733-88ac-e431c34d723d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F06 -Rezerwacja noclegów/T20 - Rezerwacja noclegu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d7c41bce-6af2-4334-be52-fb7112e7e101</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7ff5232-a397-46df-8320-bb84765d6428</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/F06 -Rezerwacja noclegów/T21 - Rezerwacja noclegu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4021b5c9-2ae9-4d24-a3aa-8afc5183fe29</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
