<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_input</name>
   <tag></tag>
   <elementGuidId>6dea922e-d22d-4265-9106-e610ea949732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-hotels_city-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
