<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click</name>
   <tag></tag>
   <elementGuidId>82c86183-92c6-4b2a-b471-e56052a460a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-hotels_city-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
