<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loader_search</name>
   <tag></tag>
   <elementGuidId>e4bd11fb-237d-405c-9956-70b49d411d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loading_flight</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
