<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Jeli ich nie ma, kliknij Pomi_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>4783106b-4c6f-4141-abc5-ed1c5c7e4d23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq24hNKLvDCcqdMiqU75Z7_1htp4fILnipVbidsWBMmf_38qe3VZSAm_7lXcUMgDbID42YN07BHTg9NBeriweAAG4k4ptXP1mDa9Aft0F3LBkHDohofuZ78stH3hMuao4VbmmKDL6djIuONwkPhATxuGXGjONniCQpKmLL2PdFB4qfvQiBLlIfl3qP-gHusRkVxv2JDr2&amp;k=6LdX3JoUAAAAAFCG5tm0MFJaCF3LKxUN4pVusJIF&amp;id=2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Support/Page_Contact - PHPTRAVELS/iframe_concat(id(, , fadein, , )div3div4ifr_6e2f04</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24hNKLvDCcqdMiqU75Z7_1htp4fILnipVbidsWBMmf_38qe3VZSAm_7lXcUMgDbID42YN07BHTg9NBeriweAAG4k4ptXP1mDa9Aft0F3LBkHDohofuZ78stH3hMuao4VbmmKDL6djIuONwkPhATxuGXGjONniCQpKmLL2PdFB4qfvQiBLlIfl3qP-gHusRkVxv2JDr2&amp;k=6LdX3JoUAAAAAFCG5tm0MFJaCF3LKxUN4pVusJIF&amp;id=2')])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AGdBq24hNKLvDCcqdMiqU75Z7_1htp4fILnipVbidsWBMmf_38qe3VZSAm_7lXcUMgDbID42YN07BHTg9NBeriweAAG4k4ptXP1mDa9Aft0F3LBkHDohofuZ78stH3hMuao4VbmmKDL6djIuONwkPhATxuGXGjONniCQpKmLL2PdFB4qfvQiBLlIfl3qP-gHusRkVxv2JDr2&amp;k=6LdX3JoUAAAAAFCG5tm0MFJaCF3LKxUN4pVusJIF&amp;id=2']</value>
   </webElementXpaths>
</WebElementEntity>
