<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Jeli ich nie ma, kliknij Pomi_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>e6b079fb-be3f-4026-863b-5853b88f868f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AGdBq25998GskKVHEdDou9fnDlbURftfRtsvHDok2K29IWQGCgiw3UA4lJMKlOePc3Q0f7JTFLYY-OtnRoflihU1bGGgilpJNPF3jS7zOw0cXR9H6u1eXK3BTdmrxBYboshzSOaKKliulmEMQEbIWojiWVUG3CGahH_-Ji8Zh_uHqyktwsM-Uk9JJ7b3h1FrfU2IVbBZJkET&amp;k=6LdX3JoUAAAAAFCG5tm0MFJaCF3LKxUN4pVusJIF</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Support/Page_Contact - PHPTRAVELS/iframe_concat(id(, , fadein, , )div3div4ifr_6e2f04</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AGdBq25998GskKVHEdDou9fnDlbURftfRtsvHDok2K29IWQGCgiw3UA4lJMKlOePc3Q0f7JTFLYY-OtnRoflihU1bGGgilpJNPF3jS7zOw0cXR9H6u1eXK3BTdmrxBYboshzSOaKKliulmEMQEbIWojiWVUG3CGahH_-Ji8Zh_uHqyktwsM-Uk9JJ7b3h1FrfU2IVbBZJkET&amp;k=6LdX3JoUAAAAAFCG5tm0MFJaCF3LKxUN4pVusJIF')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AGdBq25998GskKVHEdDou9fnDlbURftfRtsvHDok2K29IWQGCgiw3UA4lJMKlOePc3Q0f7JTFLYY-OtnRoflihU1bGGgilpJNPF3jS7zOw0cXR9H6u1eXK3BTdmrxBYboshzSOaKKliulmEMQEbIWojiWVUG3CGahH_-Ji8Zh_uHqyktwsM-Uk9JJ7b3h1FrfU2IVbBZJkET&amp;k=6LdX3JoUAAAAAFCG5tm0MFJaCF3LKxUN4pVusJIF']</value>
   </webElementXpaths>
</WebElementEntity>
